title:
author:
  name: AK
  email: github@aklein.pro
  github: KDN-Cloud

description: >
  Music notes and thoughts.

url: https://b.aklein.studio
repository: "KDN-Cloud/b.aklein.studio"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

social:
  type: Decentralized Social Network
  name: AK
  links: https://aklein.pro

# https://github.com/jekyll/minima
remote_theme: jekyll/minima@master
minima:
  skin: auto # auto, dark, light, solarized
  social_links:
    - { platform: github, user_url: "https://github.com/variablenix" }

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
