title: Tone's Music
author:
  name: Tone (ak)
  email: github@aklein.pro
  github: KDN-Cloud

description: A technical annex of aklein.studio—documenting the intersection of music production and DJ culture.

url: https://b.aklein.studio
repository: "KDN-Cloud/b.aklein.studio"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social:
  type: Decentralized Social Network
  name: AK
  links: https://aklein.pro

theme: jekyll-theme-slate  # jekyll-theme-midnight, jekyll-theme-cayman

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
